default-econ-balance: 100
teleport-wait-time: 10
teleportPermissions: #Give people the permission vexus.teletime.{name}
  pro: 5 #vexus.teletime.pro
  mod: 2 #vexus.teletime.mod etc

cooldowns:
   heal:
     default: 3600 #one hour in seconds
   feed:
     default: 3600 #one hour in seconds
   chatspam:
     default: 1

default-homes: 1
homes:
   pro: -1
motds:
   - "&7Welcome to &aVexus&7!"
   - "&7Come join &aVexus&7!"

spawn-regions:
   world:
   - spawn

announce-length: 20
pvp-tag-time: 15